USE [master]
GO
/****** Object:  Database [python_data]    Script Date: 17/09/2024 17:26:14 ******/
CREATE DATABASE [python_data]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'python_data', FILENAME = N'C:\Users\User\Documents\SQL Server Management Studio\python_data2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'python_data_log', FILENAME = N'C:\Users\User\Documents\SQL Server Management Studio\python_data_log2.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [python_data] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [python_data].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [python_data] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [python_data] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [python_data] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [python_data] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [python_data] SET ARITHABORT OFF 
GO
ALTER DATABASE [python_data] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [python_data] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [python_data] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [python_data] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [python_data] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [python_data] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [python_data] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [python_data] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [python_data] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [python_data] SET  ENABLE_BROKER 
GO
ALTER DATABASE [python_data] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [python_data] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [python_data] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [python_data] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [python_data] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [python_data] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [python_data] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [python_data] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [python_data] SET  MULTI_USER 
GO
ALTER DATABASE [python_data] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [python_data] SET DB_CHAINING OFF 
GO
ALTER DATABASE [python_data] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [python_data] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [python_data] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [python_data] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [python_data] SET QUERY_STORE = OFF
GO
USE [python_data]
GO
/****** Object:  Table [dbo].[doctors]    Script Date: 17/09/2024 17:26:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[doctors](
	[dr_id] [int] IDENTITY(1,1) NOT NULL,
	[dr_name] [varchar](50) NOT NULL,
	[dr_seniority] [int] NULL,
	[dr_age] [int] NULL,
	[dr_category] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[dr_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [python_data] SET  READ_WRITE 
GO
USE [python_data]
GO
ALTER TABLE [dbo].[doctors]
ADD [dr_image_url] VARCHAR(255) NULL;
GO

